---
engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 60
  fixme:
    enabled: true
    config:
      strings:
      - TODO
      - FIXME
      - BUG
  phpmd:
    enabled: true
    config:
      rulesets: phpmd.xml
ratings:
  paths:
    - src/**/*.php
    - tests/**/*.php
exclude_paths:
- config/
- public/