sudo: false

language: generic

dist: trusty

env:
  global:
    - NEEDED_MODULES="lua-vips lua-resty-http lua-resty-template luacov-coveralls"
    - LUAROCKS_VERSION=2.4.4
    - VIPS_VERSION=8.7.0
    - VIPS_PRE_VERSION=alpha2
    - VIPS_TAR_VERSION=$VIPS_VERSION
    - VIPS_WARNING=0
    - TEST_COVERAGE=1
    - LUA_PATH="?;?.lua;$HOME/luarocks/share/lua/5.1/?.lua"
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH
    - PATH=$HOME/vips/bin:$HOME/luarocks/bin:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin:$PATH

cache:
  apt: true
  directories:
    - $HOME/vips
    - $HOME/luarocks

addons:
  apt:
    sources:
      - sourceline: 'deb http://openresty.org/package/ubuntu trusty main'
        key_url: 'https://openresty.org/package/pubkey.gpg'
    packages:
      - openresty
      - openresty-resty
      - libtest-nginx-perl
      - libexpat1-dev
      - gettext
      - libglib2.0-dev
      - liborc-0.4-dev
      - libfftw3-dev
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libgif-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev

before_install:
  - bash .travis/install-vips.sh
  - bash .travis/install-luarocks.sh
    --with-lua=/usr/local/openresty/luajit/
    --lua-suffix=jit-2.1.0-beta3
    --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1

install:
  - cp app/config.example.lua app/config.lua
  - if [[ ! -z ${NEEDED_MODULES} ]]; then for i in ${NEEDED_MODULES}; do luarocks install "$i"; done fi

script: prove -r t

after_success: luacov-coveralls --dryrun