version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/sites-enabled/images.nginxconf:/etc/nginx/sites-enabled/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/:/var/log/nginx
      - /dev/shm:/dev/shm
      - ./public/:/var/www/imagesweserv/public
    depends_on:
      - php
    networks:
      - front
      - back

  php:
    build: ./docker
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./logs/php-fpm/:/var/log/php-fpm
      - ./logs/php/:/var/log/php
      - /dev/shm:/dev/shm
      - .:/var/www/imagesweserv
    depends_on:
      - redis
    networks:
      - back

  redis:
    image: redis:latest
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge